### PR TITLE
Gnome shell 3.32 fixes

### PR DESCRIPTION
**Pull request by F-i-f**
This set of changes update the extension for Gnome-Shell 3.32.

### CODE REVIEW

**Review by Rmano — COMMENTED** [review]
Hmmm... wouldn't this disable the extension for the older shells? Or they will get the older extension? I am still on 3.28 (and it's working...) 
I am sorry if this is a kind of strange comment, I wrote the extension main by copy and paste and I am not so knowledgeable about the extensions ecosystem...

**Comment by F-i-f** [comment]
That won't disable or break the extension for older shells:  since they are not listed as compatible in `metadata.json`, the [Gnome Shell Extensions](https://extensions.gnome.org) web site won't offer or upgrade the extensions for Gnome Shells older than 3.32.
So on 3.28, you should be offered the old, current version.
And 3.32 users will be able to use the extension again (after upgrading of course).

**Comment by Rmano** [comment]
Ok. Nice, I'll merge it --- and then I'll see if I remember how to release it ;-). Thank you a lot!

**Comment by Rmano** [comment]
Done, I hope I have done everything correctly... feel free to open an issue if anything is gone wrong.

**Comment by F-i-f** [comment]
It looks good, I think you can submit it to the [extensions website](https://extensions.gnome.org/upload/).

**Pull request merged**
